version: '3.8'
services:
  mongo:
    image: ramakrishna737/myown:v1
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - mongo-data:/data/db
    deploy:
      replicas: 2

volumes:
  mongo-data:


