# Use Node.js LTS version
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json & install dependencies
COPY package*.json ./
RUN npm install

# Copy application files
COPY . .



# Start the app
CMD ["node", "app.js"]
